### ISSUE TITLE
Add log level option to subscribe method

### ISSUE THREAD

**Issue by jsvd** [jordansissel/ruby-cabin#32]
The idea behind this is to allow

```ruby
logger = Cabin::Channel.get
logger.level = :info
logger.subscribe(File.open("/tmp/log", "a"), :info) # :debug would be the same as nil
logger.subscribe(STDOUT, :warn)
```

Such that:
* `logger.debug("test")` won't be sent anywhere
* `logger.info("test")` is sent only to the logfile
* `logger.fatal("test")` is sent to both

**Comment by jordansissel** [comment]
hmm, I'm open to this idea. For backwards compat, we can have subscribe(IO) with no level default to :debug
